apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab5deploy
  name: lab5deploy
  namespace: chapter4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab5deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lab5deploy
    spec:
      containers:
        - image: k8sworkout/ch04:lab5
          name: ch04
          resources: {}
status: {}
