apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab9
  name: lab9
  namespace: chapter6
spec:
  containers:
    - image: k8sworkout/ch06:lab9
      name: lab9
      envFrom:
        - configMapRef:
            name: currency-api
      env:
        - name: CURRENCY_TOKEN
          valueFrom:
            secretKeyRef:
              name: currency-token
              key: token
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}