apiVersion: v1
kind: Pod
metadata:
  labels:
    run: lab3
  name: lab3
  namespace: chapter3
spec:
  containers:
    - image: k8sworkout/ch03:lab3
      name: lab3container
      imagePullPolicy: Always
  resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
